name: Example Workflow with Inputs

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Enter your name'
        required: true
        default: 'GitHubUser'
      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  

      - name: Display the inputs
        run: |
          echo "Hello, ${{ inputs.name }}!"
          echo "The environment selected is ${{ inputs.environment }}."

      - name: Run the testing powerscript file
        run: |
          pwsh -File ./scripts/test.ps1 ${{ inputs.name }} ${{ github.event.inputs.environment }}
