name: Example Workflow with Inputs

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Enter your name'
        required: true
        default: 'GitHubUser'
      environment:
        description: 'Choose environment'
        required: true
        default: 'production'
        options:
          - production
          - staging
          - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  

      - name: Display the inputs
        run: |
          echo "Hello, ${{ github.event.inputs.name }}!"
          echo "The environment selected is ${{ github.event.inputs.environment }}."

      - name: Run the testing powerscript file
        run: |
          pwsh -File ./scripts/test.ps1 ${{ github.event.inputs.name }} ${{ github.event.inputs.environment }}
